/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author Samuel
 */
public class frm_Ventas extends javax.swing.JDialog {

    /**
     * Creates new form frm_Ventas
     */
    public frm_Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cambiarImagenes("fondoP (Custom).png", "fondoP (Custom).png","fondoP (Custom).png");
        
    }

     public void cambiarImagenes(String imgProducto1, String imgProducto2,String imgProducto3) {
        ImageIcon image1 = new ImageIcon(getClass().getResource("/imgs/" + imgProducto1));
        Icon icon1 = new ImageIcon(image1.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icon1);
        
    ImageIcon image2 = new ImageIcon(getClass().getResource("/imgs/" + imgProducto2));
        Icon icon2 = new ImageIcon(image2.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
        jLabel2.setIcon(icon2);
        
        ImageIcon image3 = new ImageIcon(getClass().getResource("/imgs/" + imgProducto2));
        Icon icon3 = new ImageIcon(image3.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
        jLabel4.setIcon(icon3);
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registroFactura = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_AgregarEnTabla = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        btn_buscarProducto = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_buscarCodigo = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(515, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_registroFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        tbl_registroFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbl_registroFactura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 351, 790, 250));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setText("TOTAL A PAGAR");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(400, 10, 180, 26);

        txtTotalPagar.setEditable(false);
        jPanel4.add(txtTotalPagar);
        txtTotalPagar.setBounds(590, 10, 170, 40);

        jButton2.setText("GENERAR VENTA");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jButton2);
        jButton2.setBounds(200, 10, 150, 40);

        btnLimpiar.setText("CANCELAR");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(btnLimpiar);
        btnLimpiar.setBounds(30, 10, 150, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondoP (Custom).png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 790, 60);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 790, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        btn_AgregarEnTabla.setText("AGREGAR");
        btn_AgregarEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarEnTablaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_AgregarEnTabla);
        btn_AgregarEnTabla.setBounds(310, 100, 90, 32);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("CANTIDAD PRODUCTO");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 150, 160, 14);

        txtCosto.setEditable(false);
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCosto);
        txtCosto.setBounds(170, 100, 130, 24);

        btn_buscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-9-16.png"))); // NOI18N
        btn_buscarProducto.setBorder(null);
        btn_buscarProducto.setBorderPainted(false);
        btn_buscarProducto.setContentAreaFilled(false);
        jPanel3.add(btn_buscarProducto);
        btn_buscarProducto.setBounds(320, 60, 16, 16);

        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigoProducto);
        txtCodigoProducto.setBounds(170, 60, 130, 24);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("CODIGO PRODUCTO");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 70, 130, 14);

        btn_buscarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search-9-16.png"))); // NOI18N
        btn_buscarCodigo.setBorder(null);
        btn_buscarCodigo.setBorderPainted(false);
        btn_buscarCodigo.setContentAreaFilled(false);
        jPanel3.add(btn_buscarCodigo);
        btn_buscarCodigo.setBounds(320, 20, 16, 16);

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigo);
        txtCodigo.setBounds(170, 20, 130, 24);

        txtNombre.setEditable(false);
        jPanel3.add(txtNombre);
        txtNombre.setBounds(520, 24, 230, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("PRODUCTO");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(430, 70, 80, 14);

        txtDescripcion.setEditable(false);
        jPanel3.add(txtDescripcion);
        txtDescripcion.setBounds(520, 60, 230, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("STOCK");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(430, 110, 80, 14);

        txtStock.setEditable(false);
        txtStock.setText("45");
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        jPanel3.add(txtStock);
        txtStock.setBounds(520, 100, 110, 30);

        jTextField6.setText("jTextField6");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(340, 140, 160, 24);
        jPanel3.add(txtCantidad);
        txtCantidad.setBounds(170, 140, 140, 26);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("CLIENTE");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(430, 30, 60, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("CODIGO CLIENTE");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 30, 105, 14);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("PRECIO PRODUCTO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 110, 130, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondoP (Custom).png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 190);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 780, 200));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA DE FACTURACIÓN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 50));

        jTextField7.setEditable(false);
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 240, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 650, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondoP (Custom).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btn_AgregarEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarEnTablaActionPerformed
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_btn_AgregarEnTablaActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Ventas dialog = new frm_Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btn_AgregarEnTabla;
    public javax.swing.JButton btn_buscarCodigo;
    public javax.swing.JButton btn_buscarProducto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    public javax.swing.JTable tbl_registroFactura;
    public javax.swing.JSpinner txtCantidad;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
